### ISSUE TITLE
Parar Gen From Ronin

### ISSUE THREAD

**Issue by rogerioaguas** [ShaneMaglangit/agp#8]
Can I parse the gen from roninchain , or works only with gen from graphql?

**Comment by ShaneMaglangit** [comment]
Yes, the library supports both the 256 hex representation (GraphQL) and 512 hex (Ronin). Do note that depending on where you're extracting the gene from the RPC, you might have to do additional preprocessing.

[Refer to this](https://github.com/ShaneMaglangit/agp-npm/issues/10#issuecomment-920610775) if you're getting a seperate X and Y genes.
